INSERT INTO lugares (
    id,
    name,
    country,
    lat,
    lng,
    category,
    icon,
    period,
    desc_text,
    img,
    pais_code
) VALUES
(
    'museo_larco',
    'Museo Larco',
    'PE',
    -12.072497,
    -77.070861,
    'ARQUEOLOGIA',
    'landmark',
    'Época precolombina (3000 a.C.-1532 d.C.)',
    'El Museo Larco conserva una de las colecciones más importantes de arte del antiguo Perú, con miles de piezas arqueológicas que permiten conocer las culturas que florecieron antes de la llegada de los españoles.',
    NULL,
    'PE'
),
(
    'chan_chan',
    'Chan Chan',
    'PE',
    -8.107836,
    -79.074981,
    'PATRIMONIO',
    'landmark',
    'Siglo IX-XV (c. 850-1470 d.C.)',
    'Chan Chan fue la capital del reino Chimú y constituye una de las mayores ciudades de adobe de la América precolombina. Sus palacios, plazas y complejos ceremoniales reflejan la organización y riqueza de esta antigua civilización.',
    NULL,
    'PE'
),
(
    'puente_suspiros',
    'Puente de los Suspiros',
    'PE',
    -12.149140,
    -77.022624,
    'INFRAESTRUCTURA',
    'landmark',
    'Siglo XIX (1876)',
    'Emblemático puente de madera de Barranco construido en el siglo XIX, convertido en uno de los lugares más representativos y románticos de Lima, con vistas hacia la tradicional Bajada de los Baños.',
    NULL,
    'PE'
),
(
    'casona_sanmarcos',
    'Casona de San Marcos',
    'PE',
    -12.05461,
    -77.03223,
    'ACADEMICO',
    'landmark',
    'Siglos XVII-XIX',
    'Histórica sede de la Universidad Nacional Mayor de San Marcos, ubicada en el Parque Universitario, que actualmente funciona como centro cultural y conserva una importante arquitectura colonial y republicana.',
    NULL,
    'PE'
),
(
    'teatro_municipal',
    'Teatro Municipal de Lima',
    'PE',
    -12.045385,
    -77.034873,
    'HISTORICO',
    'landmark',
    'Siglo XX (1920)',
    'Uno de los principales teatros históricos de Lima, ubicado en el Centro Histórico y reconocido por su arquitectura de inspiración renacentista y barroca, además de su importancia en la vida cultural de la ciudad.',
    NULL,
    'PE'
),
(
    'marinera_trujillo',
    'Festival de la Marinera',
    'PE',
    -8.1116,
    -79.0288,
    'DANZA',
    'music',
    'Siglo XX (1960)',
    'Tradicional festival peruano dedicado a la marinera, una de las danzas más representativas del país, que reúne cada año a bailarines y visitantes en la ciudad de Trujillo.',
    NULL,
    'PE'
),
(
    'paracas',
    'Reserva Nacional de Paracas',
    'PE',
    -14.1531,
    -76.2806,
    'PAISAJE_NATURAL',
    'trees',
    'Siglo XX (1975)',
    'Área natural protegida de la costa peruana que combina desierto, playas, acantilados e importantes ecosistemas marinos, además de albergar una extraordinaria diversidad de aves y fauna marina.',
    NULL,
    'PE'
),
(
    'centro_historico_lima',
    'Centro Histórico de Lima',
    'PE',
    -12.0464,
    -77.0428,
    'HISTORICO',
    'landmark',
    'Siglo XVI-presente (1535-actualidad)',
    'Corazón histórico de la capital peruana, caracterizado por sus plazas, iglesias, conventos y casonas que conservan siglos de historia y reflejan la evolución de Lima desde la época colonial hasta la actualidad.',
    NULL,
    'PE'
);